// Editorial posts. Structured TS (no MDX toolchain) — matches the
// lib/catalog.ts / lib/content.ts pattern. Body is an ordered list
// of blocks the renderer maps to elements.

export type Block =
  | { t: 'h2'; text: string }
  | { t: 'p'; text: string }
  | { t: 'ul'; items: string[] }
  | { t: 'quote'; text: string }
  | { t: 'listing'; id: string; label: string } // inline featured-listing card

export type Post = {
  slug: string
  title: string
  excerpt: string
  publishedAt: string
  updatedAt: string
  author: string
  authorRole: string
  tags: string[]
  relatedListings: string[]
  body: Block[]
}

const P = (text: string): Block => ({ t: 'p', text })
const H = (text: string): Block => ({ t: 'h2', text })
const UL = (items: string[]): Block => ({ t: 'ul', items })
const QUOTE = (text: string): Block => ({ t: 'quote', text })
const L = (id: string, label: string): Block => ({ t: 'listing', id, label })

export const POSTS: Post[] = [
  {
    slug: 'getting-started-with-ai-agents',
    title: 'Getting started with AI agents: the plain-English starter guide',
    excerpt:
      'New to AI agents? Start here. What they are, what they’re good for, and exactly how to get your first one running — no code.',
    publishedAt: '2026-08-18',
    updatedAt: '2026-08-18',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['guides', 'fundamentals', 'getting-started'],
    relatedListings: ['guide-first-agent-20-min', 'first-skill-md'],
    body: [
      P('If you keep hearing “AI agents” and quietly nodding along, this is the page that fixes that. No jargon, no code, no hype — just what an agent actually is and how to get one doing real work for you today.'),
      H('What is an AI agent?'),
      P('An AI agent is a general AI — like Claude — that has been given one specific job, clear instructions for how to do it, and access to the tools it needs. A chatbot answers questions. An agent does the work: it reads the email, drafts the quote, chases the invoice, books the appointment — on its own, the same way, every time.'),
      P('The simplest way to picture it: a chatbot is a smart person you message. An agent is a smart person you hired, trained for one task, and pointed at your inbox.'),
      H('What is a “skill”?'),
      P('You don’t train an agent by re-explaining the job every time. You hand it a skill — a single file (a SKILL.md) holding the intent, the inputs, the steps and the output for one task. Drop it into the agent and it knows that job. Stack a few skills and you have an agent that runs a whole desk.'),
      UL([
        'One skill = one job, done predictably and unattended',
        'Portable — the same file works across Claude, OpenClaw and most agents',
        'Buy a proven one, or write your own — both work the same way',
      ]),
      H('What can it actually do for a small business?'),
      P('Real, boring, money-saving things — not science fiction:'),
      UL([
        'Answer the “do you have Saturday?” booking DMs and put them in the calendar',
        'Turn a job photo plus a few notes into an itemised quote',
        'Chase overdue invoices in a tone that keeps the client',
        'Triage after-hours calls so you only wake for real emergencies',
        'Write the weekly client update from your task list, in your voice',
      ]),
      H('How to get started (no code)'),
      UL([
        'Pick ONE job that eats your time every week — start narrow',
        'Pick a platform — Claude is the easiest place to begin',
        'Get the skill — buy a ready-made one, or write your own',
        'Drop it in and run it on one real example',
        'Edit the voice/config block once so it sounds like you, then let it run',
      ]),
      QUOTE('Don’t try to automate everything. Automate the one task you’d pay a person to take off your plate, prove it works, then add the next.'),
      H('Where to go next'),
      P('To be running in one sitting, start with the 20-minute guide. To understand the building block first, read up on the SKILL.md file.'),
      L('guide-first-agent-20-min', 'Your first agent in 20 minutes'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
      P('When you’re ready for something that already works, the marketplace is full of skills and full agent setups built by people who run them in real businesses — drop one in and you’re going today.'),
    ],
  },
  {
    slug: 'what-is-a-skill-md-file',
    title: 'What is a SKILL.md file (and why it matters in 2026)',
    excerpt:
      'The single file that turns a general AI into a specialist at one job — explained without the jargon.',
    publishedAt: '2026-05-20',
    updatedAt: '2026-05-20',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['skill.md', 'guides', 'fundamentals'],
    relatedListings: ['first-skill-md', 'agent-prompt-patterns'],
    body: [
      P('Every working AI agent is a stack of small, specific capabilities. A SKILL.md file is how you hand the agent one of those capabilities — cleanly, repeatably, without re-explaining it every time.'),
      H('The short version'),
      P('A SKILL.md is a Markdown file with a small header (what the skill is, what tools it can touch) and a body that tells the agent exactly how to do one job: the intent, the inputs, the steps, the output. You drop it into your agent’s skills folder. The agent picks it up. Done.'),
      H('Why a file, not a prompt?'),
      P('Prompts evaporate. A file is versioned, shareable, and reviewable. It survives a model upgrade. It can be sold, bought, and improved by someone who is not you. That is the whole basis of a skills marketplace.'),
      UL([
        'Portable — the same file works across Claude, OpenClaw, and most agents',
        'Reviewable — a human can read it before trusting it',
        'Composable — ten small skills beat one giant prompt',
      ]),
      H('What good looks like'),
      P('A good SKILL.md does one thing. It names the failure mode it solves. It is boring to read, which is the point — boring is predictable, and predictable is what you want running unattended.'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
      P('If you are writing your own, start with the guide above. If you would rather buy one that already works, the catalogue is full of them.'),
    ],
  },
  {
    slug: 'claude-vs-chatgpt-small-business',
    title: 'Claude vs ChatGPT for small business automation',
    excerpt:
      'Both can run your back office. Here is the honest difference for a non-technical operator.',
    publishedAt: '2026-05-23',
    updatedAt: '2026-05-23',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['claude', 'chatgpt', 'comparison'],
    relatedListings: ['review-responder', 'daily-summary-email'],
    body: [
      P('If you run a small business and want an agent doing real work — quoting, replying, summarising — you will end up choosing between Claude and ChatGPT. Here is the version without the benchmark charts.'),
      H('Where Claude wins'),
      P('Long, structured instructions. SKILL.md-style files were practically designed for the way Claude follows multi-step instructions and respects tool boundaries. If you are buying drop-in skills, Claude is the path of least resistance.'),
      H('Where ChatGPT wins'),
      P('Install base and familiarity. Your team probably already uses it. Custom GPTs are a low-friction way to get a non-technical person running a skill without touching a settings panel they fear.'),
      H('The honest answer'),
      P('It matters less than the skill itself. A well-built skill ports between both. Pick the one your team will actually open every morning, then buy skills tagged for it.'),
      L('review-responder', 'Customer review responder'),
      L('daily-summary-email', 'Daily summary email'),
    ],
  },
  {
    slug: 'ai-agent-for-electricians',
    title: 'How to build an AI agent for electricians (real example)',
    excerpt:
      'From “I quote at 9pm” to quotes out on site, follow-ups handled, certs never missed.',
    publishedAt: '2026-05-27',
    updatedAt: '2026-05-27',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['electricians', 'claude', 'case-study'],
    relatedListings: ['electrician-ops-setup', 'compliance-cert-reminder'],
    body: [
      P('A two-van electrical business had the same problem every trade business has: the job stops at 5pm, the office work starts at 9pm, and the good leads went cold while the quote sat unwritten.'),
      H('What they automated'),
      UL([
        'Quote from a photo + a voice note, on site',
        'Follow-up until the quote is won or dead',
        'Certificate-of-compliance tracking that nags until filed',
        'Polite debtor chasing that keeps the customer',
      ]),
      H('How it was wired'),
      P('No code. An Agent Setup dropped into their agent, connected to Xero and a job-management tool with the included flows. Setup was an evening, once.'),
      QUOTE('We stopped losing the “did they ever get back to me” jobs. That was the whole game.'),
      L('electrician-ops-setup', 'Sparky Ops, wired'),
      P('The full setup is in the catalogue. If you only fix one thing first, fix compliance certs — it is the cheapest listing and the one that stops a fine.'),
      L('compliance-cert-reminder', 'Compliance cert chaser'),
    ],
  },
  {
    slug: 'n8n-vs-make-vs-zapier-for-ai-agents',
    title: 'n8n vs Make vs Zapier for AI agents',
    excerpt:
      'Which one to wire your agent into when you are not a developer — and the one to avoid for this job.',
    publishedAt: '2026-05-30',
    updatedAt: '2026-05-30',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['n8n', 'make', 'zapier', 'comparison'],
    relatedListings: ['wire-claude-and-n8n', 'first-skill-md'],
    body: [
      P('You bought a skill. Now it needs to touch your real tools — your inbox, your invoicing, your job board. That connective layer is where n8n, Make, and Zapier live. They are not the agent. They are the wiring.'),
      H('Zapier'),
      P('Easiest to start, hardest to scale. If your skill does one trigger and one action, Zapier gets you live tonight. Costs climb fast once a skill fires hundreds of times a day, and complex branching gets ugly.'),
      H('Make'),
      P('The middle. Visual, cheaper per operation than Zapier, handles branching and loops without a fight. The learning curve is a weekend, not an hour. Most non-technical operators settle here.'),
      H('n8n'),
      P('The one we tag most skills for. Self-hostable, no per-operation tax, and it does not flinch at the multi-step flows real agent work needs. It asks more of you up front and pays it back every month after.'),
      H('The honest call'),
      P('Start on whatever you already pay for. Move to n8n the first time a bill or a branching limit makes you wince. The skill itself ports between all three — that is the point of buying one built properly.'),
      L('wire-claude-and-n8n', 'Wire Claude into n8n'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
    ],
  },
  {
    slug: 'bookkeepers-bas-with-an-ai-agent',
    title: 'How bookkeepers are handling BAS with an AI agent',
    excerpt:
      'The quarterly scramble, automated down to a review-and-lodge. A real workflow, not a demo.',
    publishedAt: '2026-06-03',
    updatedAt: '2026-06-03',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['bookkeeping', 'bas', 'case-study'],
    relatedListings: ['bas-prep-assistant', 'receipt-parser', 'bookkeeper-agent-setup'],
    body: [
      P('BAS time is not hard. It is just relentless — chasing receipts, coding the odd ones, reconciling, then sanity-checking before lodging. A bookkeeper running a dozen clients does that loop a dozen times a quarter.'),
      H('What gets automated'),
      UL([
        'Receipts in from email and photo, parsed and coded',
        'Outliers flagged for a human, not silently guessed',
        'A reconciliation pass with the discrepancies listed plainly',
        'A BAS-ready summary you review, not one that lodges itself',
      ]),
      H('The line we hold'),
      P('The agent prepares. A human lodges. Anything touching a tax authority should have a person who signs off — the skill is built to stop at exactly that line, on purpose.'),
      L('receipt-parser', 'Receipt parser'),
      L('bas-prep-assistant', 'BAS prep assistant'),
      QUOTE('It turned three days of quarterly grind into an afternoon of checking.'),
      P('If you run a book of clients, the full setup wires the lot together. Start with the receipt parser if you want one win this week.'),
      L('bookkeeper-agent-setup', 'Bookkeeper agent setup'),
    ],
  },
  {
    slug: 'best-ai-agent-platforms-non-technical',
    title: 'The best AI agent platforms for non-technical operators',
    excerpt:
      'You do not need to code. You do need to pick the right place to stand. Here is the shortlist.',
    publishedAt: '2026-06-06',
    updatedAt: '2026-06-06',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['platforms', 'beginners', 'comparison'],
    relatedListings: ['guide-first-agent-20-min', 'first-skill-md'],
    body: [
      P('Every week someone asks which platform to use to run an agent for their business. The honest answer is shorter than the marketing makes it sound.'),
      H('If you want it working today'),
      P('Claude with skills. Drop a SKILL.md in, it runs. The least to learn, the most that ports later. This is where we point most first-timers.'),
      H('If your team already lives in ChatGPT'),
      P('Use that. A custom GPT is a low-fear way to get a non-technical person running a skill without a settings panel they dread. Familiarity beats theoretically-better.'),
      H('If you need it touching other tools'),
      P('You will add n8n or Make underneath. That is plumbing, not a platform choice — pick the agent first, wire it second.'),
      H('What does not matter'),
      P('Benchmarks. Model leaderboards. The thing that decides whether this works is whether the skill running on it was built by someone who did the job. Pick the platform your team will open every morning, then buy skills built for it.'),
      L('guide-first-agent-20-min', 'Your first agent in 20 minutes'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
    ],
  },
  {
    slug: 'how-to-price-a-skill-you-built',
    title: 'How to price a skill you built',
    excerpt:
      'Underprice and it looks broken. Overprice and it never sells. Where the number actually sits.',
    publishedAt: '2026-06-10',
    updatedAt: '2026-06-10',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['creators', 'pricing', 'guides'],
    relatedListings: ['guide-pricing-your-skill', 'first-skill-md'],
    body: [
      P('You built something that works. Now you have to put a number on it, and the number is doing more work than you think — it is the first signal a buyer reads about whether this is real.'),
      H('Price the outcome, not the file'),
      P('Nobody buys a Markdown file. They buy the three hours a week it gives back, or the fine it stops. Anchor to what the problem costs them, then take a fraction of it.'),
      H('Cheap is not a strategy'),
      P('A skill priced like a coffee reads like a toy. The buyers you want — operators with a real problem — will skip it because the price says it cannot be serious. Confidence is part of the product.'),
      H('Where most land'),
      UL([
        'A single sharp skill: enough to mean it, low enough to try',
        'A guide that teaches a method: more — you are selling judgement',
        'A full agent setup: the most — it replaces a process, not a task',
      ]),
      P('You keep the large majority of every sale here, so the right price is the one that respects the buyer and the work — not the lowest one you can stomach.'),
      L('guide-pricing-your-skill', 'Pricing your skill'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
    ],
  },
  {
    slug: 'ai-agent-for-plumbers',
    title: 'AI agent for plumbers: quote on site, get paid faster',
    excerpt:
      'The job ends at 5. The quoting and chasing should not start at 9. Here is the fix, plumber-specific.',
    publishedAt: '2026-06-13',
    updatedAt: '2026-06-13',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['plumbers', 'trades', 'case-study'],
    relatedListings: ['plumber-quote-engine', 'debtor-chase-skill', 'tradie-agent-setup'],
    body: [
      P('A plumber loses money in two places that have nothing to do with plumbing: the quote that never got written, and the invoice that never got chased. Both happen after hours, when you are done.'),
      H('Quote before you leave the driveway'),
      P('Photo, voice note, done. The agent turns what you saw into a priced quote and sends it before the next job. The lead is still warm. That is the whole margin.'),
      H('Chase without being the bad guy'),
      P('Polite, scheduled, persistent debtor follow-up that keeps the customer. You stop being the one who has to send the awkward text, and the money still comes in.'),
      QUOTE('The quotes go out same day now. We are not the cheapest and we still win them, because we are the first.'),
      L('plumber-quote-engine', 'Plumber quote engine'),
      L('debtor-chase-skill', 'Debtor chase'),
      P('Want it all wired together with your job tool and Xero? The trade setup is one evening, once.'),
      L('tradie-agent-setup', 'Tradie agent setup'),
    ],
  },
  {
    slug: 'human-built-vs-auto-generated-skills',
    title: 'Human-built vs auto-generated agent skills',
    excerpt:
      'Every big lab now has a skills store. Here is why a marketplace of human-tested ones still matters.',
    publishedAt: '2026-06-17',
    updatedAt: '2026-06-17',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['positioning', 'quality', 'fundamentals'],
    relatedListings: ['agent-prompt-patterns', 'first-skill-md'],
    body: [
      P('Anthropic, OpenAI, Google, and the rest are all shipping skill libraries. Most of what fills them is model-generated — plausible, generic, and never run against a real business on a bad day.'),
      H('The gap auto-generation cannot close'),
      P('A generated skill knows what a quote looks like. It does not know that this trade always gets burned on variations, or that this clinic must never confirm a booking without a deposit. That knowledge comes from doing the job, getting it wrong, and fixing it.'),
      H('What human-built actually buys you'),
      UL([
        'It has failed already — somewhere other than your business',
        'It stops at the lines a person decided were dangerous',
        'Someone can tell you why it works, not just that it does',
      ]),
      H('Why this is the whole point'),
      P('Every skill here was built by someone who needed it, ran it, and sells it because it held up. That is not a feature we added. It is the only reason to choose a marketplace over a generated list inside a model.'),
      L('agent-prompt-patterns', 'Agent prompt patterns'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
    ],
  },
  {
    slug: 'ai-for-real-estate-agents',
    title: 'AI for real estate agents: never let a lead go cold',
    excerpt:
      'The enquiry that came in at 8pm Saturday is the one you lost. An agent that does not sleep fixes that.',
    publishedAt: '2026-06-20',
    updatedAt: '2026-06-20',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['real-estate', 'lead-response', 'case-study'],
    relatedListings: ['real-estate-agent-setup', 'after-hours-triage'],
    body: [
      P('In real estate the lead does not wait for office hours. The portal enquiry at 8pm Saturday goes to whoever replies first, and most of the time that is not you — you were at an open or asleep.'),
      H('What the agent covers'),
      UL([
        'Instant, on-brand first reply to every enquiry, any hour',
        'Qualifies — budget, timeframe, finance — before it reaches you',
        'Books the inspection or call straight into your calendar',
        'Hands you a warm, sorted lead instead of a cold form',
      ]),
      H('Where the human stays in'),
      P('It never negotiates and never makes promises on price. It buys you the first ten minutes so the relationship is still yours to win.'),
      QUOTE('We were losing weekend enquiries to faster agents. Now we are the fast agent.'),
      L('after-hours-triage', 'After-hours triage'),
      L('real-estate-agent-setup', 'Real estate agent setup'),
    ],
  },
  {
    slug: 'cafe-roster-and-front-desk-one-agent',
    title: 'How a cafe runs its roster and front desk with one agent',
    excerpt:
      'Two of the most annoying jobs in hospitality, handled — so the owner can be on the floor, not the phone.',
    publishedAt: '2026-06-24',
    updatedAt: '2026-06-24',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['hospitality', 'cafe', 'case-study'],
    relatedListings: ['cafe-roster-helper', 'restaurant-front-desk', 'restaurant-agent-setup'],
    body: [
      P('A small cafe loses its owner to two jobs that are pure admin: building next week’s roster around everyone’s availability, and answering the same five questions on the phone all day.'),
      H('The roster'),
      P('Availability in, constraints applied — hours, certs, who cannot close — a draft roster out for you to approve. The argument about who got the bad shift becomes a thirty-second review.'),
      H('The front desk'),
      P('Hours, bookings, “are you dog friendly”, “do you do gluten free” — answered instantly, consistently, without pulling someone off the machine. Anything real still rings through.'),
      QUOTE('I got my Sunday night back. That used to be roster night.'),
      L('cafe-roster-helper', 'Cafe roster helper'),
      L('restaurant-front-desk', 'Restaurant front desk'),
      P('Running a bigger venue? The full hospitality setup wires bookings, comms, and roster together.'),
      L('restaurant-agent-setup', 'Restaurant agent setup'),
    ],
  },
  {
    slug: 'what-to-check-before-you-trust-a-skill',
    title: 'What to check before you trust a skill from a marketplace',
    excerpt:
      'A five-minute review that tells you whether a skill is safe to point at your real business.',
    publishedAt: '2026-06-27',
    updatedAt: '2026-06-27',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['buyers', 'safety', 'fundamentals'],
    relatedListings: ['first-skill-md', 'agent-prompt-patterns'],
    body: [
      P('A skill is just instructions you are about to let run against your inbox, your customers, or your money. Before you trust one, read it like you would a contractor’s quote — for five minutes.'),
      H('Read it, do not just run it'),
      P('A good skill is boring and legible. If you cannot follow what it does in a plain read, that is not sophistication — it is a risk you cannot see.'),
      H('Find the stop lines'),
      UL([
        'Where does it hand back to a human, and is that the right place?',
        'What does it refuse to do — send money, confirm without a deposit, lodge anything?',
        'What does it touch, and does that match what it claims to need?',
      ]),
      H('Who built it'),
      P('The thing worth paying for is that a person did this job, got it wrong, and fixed it. A skill with a named builder who can tell you why it works beats a generated one that only says that it does.'),
      P('If you write your own, the SKILL.md guide covers the safe shape. If you are buying, every listing here names its builder on purpose.'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
      L('agent-prompt-patterns', 'Agent prompt patterns'),
    ],
  },
  {
    slug: 'ai-agent-for-builders',
    title: 'AI agent for builders: site running, office not on fire',
    excerpt:
      'The job stays on site. The admin does not have to follow you home. A builder-specific setup.',
    publishedAt: '2026-07-01',
    updatedAt: '2026-07-01',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['builders', 'construction', 'trades', 'case-study'],
    relatedListings: ['builder-site-admin', 'maintenance-triage', 'tradie-agent-setup'],
    body: [
      P('A builder’s day is on site. The variations, the supplier chase, the “when can you start” messages — that all piles up for after dark, and the jobs that need a fast answer go to whoever answered first.'),
      H('What gets handled'),
      UL([
        'Inbound enquiries triaged and answered while you are on the tools',
        'Variations captured and priced before they are forgotten',
        'Maintenance and callback requests sorted by urgency, not by who shouted loudest',
        'Supplier and subbie follow-ups that do not need you to remember them',
      ]),
      H('Where the human stays'),
      P('It never commits to a start date or a final price. It buys you the first reply and the paperwork — you keep every decision that costs money.'),
      QUOTE('The variations stopped slipping. That alone paid for it the first month.'),
      L('builder-site-admin', 'Builder site admin'),
      L('maintenance-triage', 'Maintenance triage'),
      P('Want the lot wired into your job tool and accounting? The trade setup is one evening, once.'),
      L('tradie-agent-setup', 'Tradie agent setup'),
    ],
  },
  {
    slug: 'ai-for-dental-practices-no-shows',
    title: 'AI for dental practices: kill the no-shows',
    excerpt:
      'An empty chair is the most expensive thing in the practice. Recalls and reminders, automated.',
    publishedAt: '2026-07-04',
    updatedAt: '2026-07-04',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['dental', 'clinics', 'healthcare', 'case-study'],
    relatedListings: ['dental-recall-engine', 'clinic-front-desk'],
    body: [
      P('A dental practice does not lose money on hard cases. It loses it on the recall that never went out and the chair that sat empty at 2pm because nobody chased the reminder.'),
      H('The recall engine'),
      P('Patients due back get reached on time, in the practice’s voice, until they book or clearly decline. The list stops being a job nobody owns and becomes a system that runs itself.'),
      H('The front desk'),
      P('Hours, costs, “do you take my health fund”, rescheduling — answered instantly so the team is with the patient in the room, not the phone on the desk.'),
      H('The line that matters'),
      P('It books, reminds, and answers. It never gives clinical advice — that hands to a person, every time, by design.'),
      QUOTE('Our recall list was a guilt pile. Now it is just done.'),
      L('dental-recall-engine', 'Dental recall engine'),
      L('clinic-front-desk', 'Clinic front desk'),
    ],
  },
  {
    slug: 'ai-for-personal-trainers-and-coaches',
    title: 'AI for personal trainers and coaches: onboarding without the grind',
    excerpt:
      'You sell the coaching, not the admin. Hand the intake, check-ins, and chasing to an agent.',
    publishedAt: '2026-07-08',
    updatedAt: '2026-07-08',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['coaches', 'personal-training', 'fitness', 'case-study'],
    relatedListings: ['pt-onboarding-flow', 'coach-client-engine', 'coach-agent-setup'],
    body: [
      P('Every new client is the same five steps: intake form, goals call, plan sent, first check-in, keep them accountable. Do that solo across thirty clients and the admin eats the hours you should be coaching in.'),
      H('What the agent runs'),
      UL([
        'Onboarding from “signed up” to “first session booked” without you touching it',
        'Scheduled check-ins that actually go out, every week',
        'Gentle accountability nudges that keep clients from ghosting',
        'A weekly digest so you walk into every session already briefed',
      ]),
      H('Where you stay'),
      P('It never writes the program or the coaching. It clears the runway so the part only you can do gets all your attention.'),
      QUOTE('I took on ten more clients without hiring. The admin just stopped being mine.'),
      L('pt-onboarding-flow', 'PT onboarding flow'),
      L('coach-client-engine', 'Coach client engine'),
      P('Coaching at scale? The full coach setup wires intake, check-ins, and reporting together.'),
      L('coach-agent-setup', 'Coach agent setup'),
    ],
  },
  {
    slug: 'ai-for-recruiters-screen-and-schedule',
    title: 'AI for recruiters: screen and schedule on autopilot',
    excerpt:
      'The best candidate goes to the recruiter who replied first. Be that recruiter, at 2am.',
    publishedAt: '2026-07-11',
    updatedAt: '2026-07-11',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['recruiters', 'recruiting', 'hiring', 'case-study'],
    relatedListings: ['recruiter-screen-schedule', 'first-skill-md'],
    body: [
      P('Recruiting is a speed game played with a full inbox. The applicant you want is also talking to three other agencies, and the slow first reply is the lost placement.'),
      H('What gets automated'),
      UL([
        'Every applicant acknowledged immediately, not three days later',
        'First-pass screening against the must-haves before they reach you',
        'Interview scheduling booked straight into the calendar',
        'A clean shortlist on your desk instead of a 200-CV inbox',
      ]),
      H('Where judgement stays'),
      P('It never makes the hire call or rejects on anything subjective. It does the triage so your time goes to the conversations that place people.'),
      QUOTE('We doubled the roles we could run without doubling the desk.'),
      L('recruiter-screen-schedule', 'Recruiter screen + schedule'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
    ],
  },
  {
    slug: 'ai-for-ecommerce-returns-and-wismo',
    title: 'AI for ecommerce: returns and “where is my order” without a support team',
    excerpt:
      'Two questions are most of your tickets. Automate them and support stops being the bottleneck.',
    publishedAt: '2026-07-15',
    updatedAt: '2026-07-15',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['ecommerce', 'support', 'retail', 'case-study'],
    relatedListings: ['returns-and-wismo', 'ecom-support-agent-setup', 'review-responder'],
    body: [
      P('Look at your support inbox. Most of it is two questions: “where is my order” and “how do I return this”. They are not hard. They are just constant, and they drown the tickets that actually need a human.'),
      H('What the agent takes'),
      UL([
        'WISMO answered with the real tracking status, instantly',
        'Returns started, labelled, and explained without a back-and-forth',
        'Reviews responded to in your brand voice, good and bad',
        'Anything genuinely tricky escalated with the context attached',
      ]),
      H('The boundary'),
      P('It never issues a refund on its own or argues policy. It clears the volume so a person handles the cases that need one.'),
      QUOTE('Support went from a queue we dreaded to a thing that mostly handles itself.'),
      L('returns-and-wismo', 'Returns + WISMO'),
      L('review-responder', 'Customer review responder'),
      P('Selling at volume? The ecommerce support setup wires it all into your store and helpdesk.'),
      L('ecom-support-agent-setup', 'Ecommerce support setup'),
    ],
  },
  {
    slug: 'skill-vs-guide-vs-agent-setup',
    title: 'Skill vs Guide vs Agent Setup: which to buy first',
    excerpt:
      'Three things on the marketplace, one of them is right for where you are. Here is how to tell.',
    publishedAt: '2026-07-18',
    updatedAt: '2026-07-18',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['buyers', 'fundamentals', 'getting-started'],
    relatedListings: ['first-skill-md', 'guide-first-agent-20-min', 'tradie-agent-setup'],
    body: [
      P('Every listing here is one of three things. Buying the wrong one for where you are is the fastest way to decide “this AI stuff is not for me” when really you just started in the wrong place.'),
      H('A Skill — when you have one job that annoys you'),
      P('One job, done sharp. A skill is a small bundle — usually a SKILL.md plus the configs, schemas, and example inputs it needs — built for a single repetitive task you can name in a sentence. The cheapest way to find out this stuff actually works on your business.'),
      H('A Guide — when you want to understand it'),
      P('You are not buying a file, you are buying someone’s judgement on how to do this well. Buy a guide when you want to build it yourself but not learn it the hard way.'),
      H('An Agent Setup — when you want the outcome, not the project'),
      P('The whole thing, wired. Buy a setup when you want a process replaced, not a task — and you would rather spend an evening once than figure it out across months.'),
      H('The honest order'),
      P('Most people should start with one cheap skill that fixes a real annoyance, feel it work, then jump straight to the setup for their trade. The guide is for the ones who want to build.'),
      L('first-skill-md', 'Your first SKILL.md, the right way'),
      L('guide-first-agent-20-min', 'Your first agent in 20 minutes'),
      L('tradie-agent-setup', 'Tradie agent setup'),
    ],
  },
  {
    slug: 'start-free-skills-to-try-before-you-pay',
    title: 'Start free: the skills to try before you pay a cent',
    excerpt:
      'You do not have to trust us on faith. Run a free one against your real work first.',
    publishedAt: '2026-07-22',
    updatedAt: '2026-07-22',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['buyers', 'free', 'getting-started'],
    relatedListings: ['free-first-agent-guide', 'free-invoice-parser', 'free-review-responder-starter', 'free-skillmd-cheatsheet'],
    body: [
      P('The fastest way to know if a drop-in skill works for you is to run one — not read about one. So there are free ones, built to the same standard as the paid catalogue, made to be tried on your real work.'),
      H('If you have never run an agent'),
      P('Start with the free first-agent guide. Twenty minutes, no card, and at the end you have an agent doing one real thing. That is the whole proof of concept.'),
      L('free-first-agent-guide', 'Your first agent — free guide'),
      H('If you want to feel it work today'),
      UL([
        'Free invoice parser — point it at a messy invoice, watch it come back clean',
        'Free review-responder starter — see it draft a reply in your voice',
        'Free SKILL.md cheatsheet — the shape of a good skill, on one page',
      ]),
      L('free-invoice-parser', 'Free invoice parser'),
      L('free-review-responder-starter', 'Free review-responder starter'),
      P('Run a free one against your actual work. If it holds up — and it will — the paid catalogue is the same builders, going deeper.'),
      L('free-skillmd-cheatsheet', 'Free SKILL.md cheatsheet'),
    ],
  },
  {
    slug: 'ai-for-vets-end-phone-tag',
    title: 'AI for vet clinics: end the phone tag',
    excerpt:
      'Worried owners, a ringing phone, a team that needs to be with the animal. An agent fixes the gap.',
    publishedAt: '2026-07-25',
    updatedAt: '2026-07-25',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['veterinary', 'clinics', 'healthcare', 'case-study'],
    relatedListings: ['vet-phone-tag-killer', 'clinic-front-desk'],
    body: [
      P('A vet clinic runs on a phone that never stops, staffed by people who should be with the patient. Every unanswered call is a worried owner who might just drive to whoever picked up.'),
      H('What the agent covers'),
      UL([
        'Bookings, hours, and “do you do after-hours” answered the moment they ask',
        'Routine questions handled so the nurse is not the switchboard',
        'Callbacks and follow-ups captured and chased, not lost on a sticky note',
        'Urgent cases flagged straight to a person, fast',
      ]),
      H('The hard line'),
      P('It never triages a sick animal or gives clinical advice. Anything that smells urgent goes to a human immediately — that boundary is the whole point of building it carefully.'),
      QUOTE('The phone stopped owning the front desk. The team is back with the animals.'),
      L('vet-phone-tag-killer', 'Vet phone-tag killer'),
      L('clinic-front-desk', 'Clinic front desk'),
    ],
  },
  {
    slug: 'ai-for-salons-fill-the-chair',
    title: 'AI for salons and barbers: fill the chair from the DMs',
    excerpt:
      'The booking request comes in on Instagram at 9pm. You see it Tuesday. That gap is the empty chair.',
    publishedAt: '2026-07-29',
    updatedAt: '2026-07-29',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['salons', 'barbers', 'beauty', 'case-study'],
    relatedListings: ['salon-booking-dms', 'clinic-front-desk'],
    body: [
      P('A salon’s bookings do not come through a tidy form anymore. They come as DMs, late, on a day off — and the ones that do not get a fast reply just book somewhere that answered.'),
      H('What the agent runs'),
      UL([
        'Replies to booking DMs instantly, in your voice, any hour',
        'Offers real open slots and locks them into the calendar',
        'Handles reschedules and the “what does a balayage cost” questions',
        'Nudges no-show-prone clients with a confirmation the day before',
      ]),
      H('Where you stay'),
      P('It never invents a price for custom work or promises a stylist by name without the diary backing it. It catches the booking while it is hot — you keep the chair full.'),
      QUOTE('We were losing weekend DMs to slower salons. Now the DM is the booking.'),
      L('salon-booking-dms', 'Salon booking DMs'),
      L('clinic-front-desk', 'Front desk, answered'),
    ],
  },
  {
    slug: 'ai-for-tutors-plan-and-mark-faster',
    title: 'AI for tutors: plan sessions and mark in a fraction of the time',
    excerpt:
      'You are paid to teach, not to lesson-plan at midnight and mark on Sunday. Hand both to an agent.',
    publishedAt: '2026-08-01',
    updatedAt: '2026-08-01',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['tutors', 'tutoring', 'education', 'case-study'],
    relatedListings: ['tutor-session-planner', 'marking-assistant'],
    body: [
      P('A tutor’s billable hour is the session. Everything around it — planning the next one, marking the last one, writing the parent update — is unpaid and endless, and it scales linearly with every student you take on.'),
      H('What gets handled'),
      UL([
        'Session plans drafted to the student’s level and last week’s gaps',
        'Marking with feedback you review, not feedback you write from scratch',
        'Parent updates that actually go out, on time, sounding like you',
      ]),
      H('Where the teaching stays'),
      P('It never decides what a student needs — you do. It removes the paperwork between sessions so the next one is yours to teach, not to prepare at midnight.'),
      QUOTE('I took on six more students and my Sundays came back. Both at once.'),
      L('tutor-session-planner', 'Tutor session planner'),
      L('marking-assistant', 'Marking assistant'),
    ],
  },
  {
    slug: 'ai-for-therapists-the-admin-hour-back',
    title: 'AI for therapists and counsellors: take the admin hour back',
    excerpt:
      'Intake, conflict checks, notes scaffolding, rebooking — the work around the work, handled with care.',
    publishedAt: '2026-08-05',
    updatedAt: '2026-08-05',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['therapists', 'counselling', 'healthcare', 'case-study'],
    relatedListings: ['therapy-admin-hour', 'intake-and-conflict-check'],
    body: [
      P('A private practice loses an hour a day to the work around the work: intake forms, conflict checks, rebooking, the notes scaffold. It is necessary, it is not therapy, and it is quietly burning out the practitioner.'),
      H('What the agent takes'),
      UL([
        'Intake collected and organised before the first session',
        'Conflict-of-interest checks run against the existing caseload',
        'Rebooking and reminders handled so the gap does not go cold',
        'A clean notes scaffold ready for you to complete',
      ]),
      H('The line, held hard'),
      P('It never touches clinical content, never advises, never sees more than the admin needs. Every boundary here was drawn deliberately — that care is the reason to use a human-built skill, not a generated one.'),
      QUOTE('The hour came back. The part that matters got my full attention again.'),
      L('therapy-admin-hour', 'Therapy admin hour'),
      L('intake-and-conflict-check', 'Intake + conflict check'),
    ],
  },
  {
    slug: 'ai-for-photographers-shoot-to-invoice',
    title: 'AI for photographers: shoot to invoice without the chase',
    excerpt:
      'The shoot is the easy part. The enquiry, the booking, the gallery, the invoice — that is the business.',
    publishedAt: '2026-08-08',
    updatedAt: '2026-08-08',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['photographers', 'creative', 'case-study'],
    relatedListings: ['shoot-to-invoice', 'invoice-generator'],
    body: [
      P('A photographer’s money does not leak on the shoot. It leaks in the week around it: the enquiry that waited three days, the booking never confirmed, the invoice that sat unsent while you edited.'),
      H('What gets automated'),
      UL([
        'Enquiries answered fast with packages and real availability',
        'Bookings confirmed, deposits requested, dates locked',
        'Delivery and invoice triggered when the gallery ships',
        'Polite payment follow-up so you are not the awkward one',
      ]),
      H('Where you stay'),
      P('It never quotes a custom job blind or promises a turnaround you did not set. It runs the business so you can be behind the camera and in the edit.'),
      QUOTE('Invoices go out the day the gallery does now. That changed the cashflow entirely.'),
      L('shoot-to-invoice', 'Shoot to invoice'),
      L('invoice-generator', 'Invoice generator'),
    ],
  },
  {
    slug: 'ai-for-agencies-updates-and-content',
    title: 'AI for agencies: client updates and content that ship themselves',
    excerpt:
      'Two things eat agency margin: the weekly update nobody has time for, and content that never gets repurposed.',
    publishedAt: '2026-08-12',
    updatedAt: '2026-08-12',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['agencies', 'content', 'marketing', 'case-study'],
    relatedListings: ['weekly-client-update', 'content-repurposer', 'designer-handoff-pack'],
    body: [
      P('Agency margin dies in two places: the weekly client update that takes an hour nobody billed, and the one piece of content that should have become ten and became one.'),
      H('What the agents run'),
      UL([
        'Weekly client updates drafted from the actual work log, on schedule',
        'One asset repurposed into the week’s posts, in each client’s voice',
        'Clean designer-to-dev handoff packs so nothing gets lost in translation',
      ]),
      H('Where the judgement stays'),
      P('Strategy, creative calls, the client relationship — all yours. This clears the recurring production drag so the team’s hours go to the work clients actually pay for.'),
      QUOTE('The weekly updates stopped being a Friday tax. That is real margin back.'),
      L('weekly-client-update', 'Weekly client update'),
      L('content-repurposer', 'Content repurposer'),
      P('Handing work between design and build? The handoff pack stops the leak.'),
      L('designer-handoff-pack', 'Designer handoff pack'),
    ],
  },
  {
    slug: 'ai-for-contracts-and-proposals',
    title: 'AI for contracts and proposals: from clause to signed SOW',
    excerpt:
      'Reading the contract and writing the proposal are the slow, expensive bookends of every deal.',
    publishedAt: '2026-08-15',
    updatedAt: '2026-08-15',
    author: 'Toby Banks',
    authorRole: 'Founder, Skillzy',
    tags: ['legal', 'contracts', 'proposals', 'case-study'],
    relatedListings: ['contract-clause-explainer', 'proposal-to-sow'],
    body: [
      P('Every deal has two slow bookends: understanding the contract someone sent you, and turning the agreed scope into a proposal or SOW that does not take a day to write.'),
      H('What the agents do'),
      UL([
        'Plain-English explanation of what a clause actually means and where the risk sits',
        'The unusual or one-sided terms flagged so you read those first',
        'A discussion turned into a structured proposal or SOW draft',
      ]),
      H('Where the human decides'),
      P('It explains and drafts. It never advises you to sign, never gives legal advice, never sends anything on its own. It does the reading and the typing — the decision stays with the person who owns the risk.'),
      QUOTE('Contracts stopped being the thing I avoided until 6pm.'),
      L('contract-clause-explainer', 'Contract clause explainer'),
      L('proposal-to-sow', 'Proposal to SOW'),
    ],
  },
]

export function getAllPosts(): Post[] {
  return [...POSTS].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt))
}
export function getPost(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug)
}
export function getPostsForListing(id: string): Post[] {
  return getAllPosts().filter((p) => p.relatedListings.includes(id))
}
export function readingMinutes(p: Post): number {
  const words = p.body.reduce((acc, b) => {
    if (b.t === 'p' || b.t === 'h2' || b.t === 'quote') return acc + b.text.split(/\s+/).length
    if (b.t === 'ul') return acc + b.items.join(' ').split(/\s+/).length
    return acc
  }, 0)
  return Math.max(2, Math.round(words / 200))
}
